### ISSUE TITLE
Problème d'installation sur Windows 11 :  "cargo install lsp-ai -F llama_cpp"

### ISSUE THREAD

**Issue by patriote2047** [SilasMarvin/lsp-ai#26]
En regardant le Tuto de : [AICodeKing](https://www.youtube.com/watch?v=f9BuYU9wjMA) pour installer **LSP-AI** pour **Ollama** sur Windows 11.
Je me suis retrouvé avec ces erreurs : 
![CARGO-PROJETS - Visual Studio Code](https://github.com/SilasMarvin/lsp-ai/assets/162593633/c17029dc-6b73-4d26-ade8-ea2c5fcfc609)
J'ai donc un peu cherché et j'ai trouvé ! 

🥇 🥇 🥇 INSTALLER sur Windows 11 & Python 3.12 & Conda 🥇 🥇 🥇 

**PRE-INSTALLATION SYSTEME :** 
[Python](https://www.python.org/downloads/)
[MiniConda](https://docs.anaconda.com/free/miniconda/)
[Installer Microsoft C++ Build Tools](https://aka.ms/vs/17/release/vs_BuildTools.exe)
[Installer Rust](https://www.rust-lang.org/tools/install)
[Installer Visual Studio Code](https://code.visualstudio.com/docs/?dv=win)
[Installer LLVM 18.1.5](https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.5/LLVM-18.1.5-win64.exe) 💯  DECLARER : **COUPABLE**
>>>>Rajouter les variables ENV au système pour llama.cpp.

**INSTALLATION de LSP-AI :***
Créer un ENV conda & l'activer.
cloner le Depot.
Se déplacer dans le dossier créé.
Vérifier que Cargo est bien installer. (Redémarrer si il y a un probléme)
Lancer la commande d'installation. 
```
### Créer un ENV conda & l'activer.
conda create -n lsp-ai python=3.12 -y
conda activate lsp-ai

### cloner le Depot.
git clone https://github.com/SilasMarvin/lsp-ai.git

### Se déplacer dans le dossier créé.
cd lsp-ai

### Vérifier que Cargo est bien installer.
cargo --version 

###### Si OK ! alors on continu...
### Lancer la commande d'installation. 
cargo install lsp-ai -F llama_cpp

# Installation Terminée.

```
### Nouvelle Réponse 👍 
![toml - CARGO-PROJETS - Visual Studio Code](https://github.com/SilasMarvin/lsp-ai/assets/162593633/daafc7fb-2a47-438e-a153-6dedba2b63b4)
👍 👍 👍 
Bonne Installation...

### Installer LSP-AI pour VScode
[LSP-AI pour VScode](https://marketplace.visualstudio.com/items?itemName=SilasMarvin.lsp-ai)
[Ollama](https://ollama.com/)

_Ps: l'installation a été faite avec un .env dans 'VisualStudio" mais il n'y ne devrait pas y avoir de soucis avec conda._

### Bonus :

1. [Le Plugin dans VScode.](https://github.com/SilasMarvin/lsp-ai/wiki/Plugins)
2. [Configuration pour Ollama.](https://github.com/SilasMarvin/lsp-ai/wiki/Configuration#models)

**Comment by SilasMarvin** [comment]
Thanks for sharing! 

My primary language is English, so I'm not follow everything 100%. Please correct me where I'm wrong:

If I understand correctly, the install when running `cargo install lsp-ai -F llama_cpp` did not work for you, so you created a conda environment, cloned the repo, and then installed it. 

I don't know what dependencies you will need with Windows to make the install work, but I'm pretty sure cloning the repo didn't do anything. When you run `cargo install lsp-aI -F llama_cpp` it installs from crates.io. If you want to install it from the local repository you have to run `cargo install --path . -F llama_cpp`. 

I guess I'm confused why you created a conda environment with Python? It seems that it just happened to work because the Conda environment installed some missing libraries, I don't think that should be required to make the install work. 

Did you look into installing the missing `clang.ddl` and `libclang.dll` libraries, or did you already have them and try setting the `LIBCLANG_PATH` env variable?

If there are some additional steps to getting it working with Windows I would like to add it to the Wiki. Thanks for pointing this out!

**Comment by SilasMarvin** [comment]
I'm going to close this. It seems like an issue compiling llama.cpp on Windows which means its a https://github.com/utilityai/llama-cpp-rs not us bug. If you still have issues I recommend opening an issue on their GitHub page
